ESpareParts.Web/ViewModels/CategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ESpareParts.Web.ViewModels
{
    public class NewCategoryViewModel
    {

        public string Name { get; set; }

        public string Description { get; set; }

        public decimal Price { get; set; }

        public int CategoryID { get; set; }


    }
}

ESpareParts.Web/Controllers/CategoryController.cs
using ESpareParts.Entities;
using ESpareParts.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ESpareParts.Web.Controllers
{
    public class CategoryController : Controller
    {
        CategoriesService categoryService = new CategoriesService();

        [HttpGet]
        public ActionResult Index()
        {
            var categories = categoryService.GetCategories();

            return View(categories);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            categoryService.SaveCategory(category);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var category = categoryService.GetCategory(ID);

            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            categoryService.UpdateCategory(category);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            var category = categoryService.GetCategory(ID);

            return View(category);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            categoryService.DeleteCategory(category.ID);

            return RedirectToAction("Index");
        }
    }
}

ESpareParts.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ESpareParts.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

ESpareParts.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Category</h2>
<form method="post">
    <label> Name</label>
    <input name="Name" />
    <br />

    <label>Description</label>
    <input name="Description" />
    <br />

    <label>Image</label>
    <input type="hidden" id="ImageURL" name="ImageURL" />
    <input id="imageUpload" name="image" type="file" accept=".jpg, .png" />
    <br />
    <div class="thumb">
        <img id="categoryImage" />
    </div>
    <br />

    
        <label>Is Featured?</label>
        
                <label><input name="isFeatured" type="radio" value="True" /> True</label>
            
                <label><input name="isFeatured" type="radio" value="False" /> False</label>
    <br />
           
    <button type="submit">Save</button>
</form>

<script>
	$("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}

		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);

        	if(response.Success)
        	{
        	    $("#ImageURL").val(response.ImageURL);
        	    $("#categoryImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});
</script>

ESpareParts.Web/Views/Category/Delete.cshtml
@model ESpareParts.Entities.Category
@{
    ViewBag.Title = "Delete";
}

<h2>Delete Category</h2>

<h1>Are you sure you want to delete this Category? </h1>

<form method="post">
    <input type="hidden" name="ID" value="@Model.ID" />

    <button type="submit">Yes Delete</button>
</form>

<a href="/Index">Cancel</a>

ESpareParts.Web/Views/Category/Edit.cshtml
@model ESpareParts.Entities.Category
@{
    ViewBag.Title = "Edit";

    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;
}

<h2>Edit Category</h2>

<form method="post">
    <input type="hidden" name="ID" value="@Model.ID" />

    <br />


    <label>Name</label>
    <input name="Name" value="@Model.Name"/>

    <br />

    <label>Description</label>
    <input name="Description"  value="@Model.Description"/>

    <br />
    <label>Is Featured?</label>
    
            <input name="isFeatured" type="radio" value="True" @trueChecked /> True
            
            <input name="isFeatured" type="radio" value="False" @falseChecked /> False
        
    <br />
    <button type="submit">Save</button>

    <br />

</form>

ESpareParts.Web/Views/Category/Index.cshtml
@model List<ESpareParts.Entities.Category>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach (var category in Model)
{
    <h1>@category.Name</h1>
}
        